spring:
  mongodb:
    uri: mongodb://root:example@payment-mongodb:27017/paymentdb?authSource=admin
  kafka:
    bootstrap-servers: payment-kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: your-256-bit-secret-key-here-must-be-32-bytes

external:
  api:
    url: http://docker.internal

server:
  port: 8080