spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/payment_db}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

external:
  api:
    url: ${EXTERNAL_API_URL:http://localhost:8084/api/numbers}