spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/paymentdb
  kafka:
    bootstrap-servers: localhost:9092
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcHealthContributorAutoConfiguration

external:
  api:
    url: http://localhost:8081/evaluate

server:
  port: 8083